# Cellarwood Test Website Helm Values

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: www.cellarwood.org

resources:
  requests:
    cpu: "10m"
    memory: "16Mi"
  limits:
    cpu: "50m"
    memory: "32Mi"
