; PrusaSlicer profile — Tough Resin (SLA)
print_settings_id = imagineer-resin-tough
sla_material_settings_id = generic-tough-resin
printer_settings_id = generic-sla-145x145x175

display_width = 145
display_height = 145
max_print_height = 175
layer_height = 0.05
exposure_time = 7
initial_exposure_time = 35

material_density = 1.18
material_cost = 89.00
support_material = 1
