approval_policy = "never"
sandbox_mode = "danger-full-access"

model_provider = "my-vllm-server"
model = "Qwen/Qwen3.5-9B"

[model_providers.my-vllm-server]
name = "vllm-server"
base_url = "https://localhost:8000/v1"
wire_api = "responses"

[mcp_servers.tavily]
command = "npx"
args = ["-y", "tavily-mcp@latest"]

[mcp_servers.tavily.env]
TAVILY_API_KEY = "${TAVILY_API_KEY}"